server:
  port: 8102

spring:
  application:
    name: hello-feign-client

service:
  hello:
    name: HELLO-SERVICE
    uri: hello

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/