server:
  port: 8102

spring:
  application:
    name: hello-feign-client

service:
  hello:
    name: HELLO-SERVICE
    uri: hello
  hello1:
    uri: hello1
  hello2:
    uri: hello2
  hello3:
    uri: hello3

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/